app:
  name: "web_app"
  mode: "dev"
  port: 8087

log:
  level: "debug"
  filname: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: root
  password: 123456
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "192.168.43.223"
  port: 6379
  db: 0
  password: ""
  pool_size: 100